create extension if not exists pgcrypto;
create table if not exists public.clients(id uuid primary key default gen_random_uuid(),dni text not null unique,name text not null,phone text,address text,email text,created_by uuid references auth.users(id),created_at timestamptz default now());
create table if not exists public.credits(id uuid primary key default gen_random_uuid(),file_no text unique,client_id uuid not null references public.clients(id) on delete cascade,amount numeric(14,2) not null,installments integer not null,interest_rate numeric(8,4) default 0,frequency text default 'Mensual',first_due date,status text default 'Vigente',created_by uuid references auth.users(id),created_at timestamptz default now());
create table if not exists public.payments(id uuid primary key default gen_random_uuid(),client_id uuid not null references public.clients(id) on delete cascade,credit_id uuid references public.credits(id) on delete set null,amount numeric(14,2) not null,date date not null,method text,reference text,created_by uuid references auth.users(id),created_at timestamptz default now());
create table if not exists public.settings(id integer primary key default 1,company_name text default 'CREDICONTAFI',updated_at timestamptz default now());
insert into public.settings(id,company_name) values(1,'CREDICONTAFI') on conflict(id) do nothing;
alter table public.clients enable row level security; alter table public.credits enable row level security; alter table public.payments enable row level security; alter table public.settings enable row level security;
create policy "auth clients" on public.clients for all to authenticated using (true) with check (true);
create policy "auth credits" on public.credits for all to authenticated using (true) with check (true);
create policy "auth payments" on public.payments for all to authenticated using (true) with check (true);
create policy "auth settings" on public.settings for all to authenticated using (true) with check (true);

-- Evaluación de Negocio / Pre-evaluación
create table if not exists public.evaluation_parameters(
 id bigint generated by default as identity primary key,
 code text not null unique,
 label text not null,
 operator text not null check (operator in ('>=','<=')),
 value numeric(14,4) not null,
 updated_at timestamptz default now()
);
insert into public.evaluation_parameters(code,label,operator,value) values
('net_margin','Margen neto','>=',10),('roa','ROA','>=',3),('roe','ROE','>=',8),
('current_ratio','Liquidez corriente','>=',1.20),('debt_ratio','Nivel de endeudamiento','<=',70),
('debt_equity','Deuda / Patrimonio','<=',2.50),('dscr','DSCR / capacidad de pago','>=',1.30),
('payment_load','Carga de pago','<=',35)
on conflict(code) do nothing;
create table if not exists public.business_evaluations(
 id uuid primary key default gen_random_uuid(), client_id uuid not null references public.clients(id) on delete cascade,
 revenue numeric(14,2) default 0, net_income numeric(14,2) default 0, assets numeric(14,2) default 0,
 equity numeric(14,2) default 0, current_assets numeric(14,2) default 0, current_liabilities numeric(14,2) default 0,
 liabilities numeric(14,2) default 0, financial_debt numeric(14,2) default 0, cash_available numeric(14,2) default 0,
 requested_amount numeric(14,2) not null, term_months integer not null, monthly_rate numeric(8,4) default 0,
 estimated_payment numeric(14,2) default 0, ratios jsonb not null default '[]'::jsonb,
 result text not null check(result in ('PREAPROBADO','NO PROCEDE')),
 created_by uuid references auth.users(id), created_at timestamptz default now()
);
alter table public.credits add column if not exists evaluation_id uuid references public.business_evaluations(id) on delete set null;
alter table public.evaluation_parameters enable row level security;
alter table public.business_evaluations enable row level security;
create policy "auth evaluation parameters" on public.evaluation_parameters for all to authenticated using (true) with check (true);
create policy "auth business evaluations" on public.business_evaluations for all to authenticated using (true) with check (true);

-- Campos ampliados para edición y trazabilidad de evaluaciones existentes
alter table public.business_evaluations add column if not exists product_id uuid;
alter table public.business_evaluations add column if not exists business_activity text;
alter table public.business_evaluations add column if not exists business_years numeric(8,2) default 0;
alter table public.business_evaluations add column if not exists loan_purpose text;
alter table public.business_evaluations add column if not exists owner_experience text;
alter table public.business_evaluations add column if not exists tax_status text;
alter table public.business_evaluations add column if not exists gross_profit numeric(14,2) default 0;
alter table public.business_evaluations add column if not exists admin_expenses numeric(14,2) default 0;
alter table public.business_evaluations add column if not exists operating_expenses numeric(14,2) default 0;
alter table public.business_evaluations add column if not exists other_expenses numeric(14,2) default 0;
alter table public.business_evaluations add column if not exists sales_variation numeric(8,2) default 0;
alter table public.business_evaluations add column if not exists existing_debt_payment numeric(14,2) default 0;
alter table public.business_evaluations add column if not exists guarantee_type text;
alter table public.business_evaluations add column if not exists other_debt_payment numeric(14,2) default 0;
alter table public.business_evaluations add column if not exists financial_info_age text;
alter table public.business_evaluations add column if not exists doc_financial text;
alter table public.business_evaluations add column if not exists doc_sales text;
alter table public.business_evaluations add column if not exists doc_identity text;
alter table public.business_evaluations add column if not exists analyst_notes text;
alter table public.business_evaluations add column if not exists total_debt_payment numeric(14,2) default 0;
alter table public.business_evaluations add column if not exists score numeric(6,2) default 0;
alter table public.business_evaluations add column if not exists alerts jsonb not null default '[]'::jsonb;
alter table public.business_evaluations add column if not exists hard_fail_count integer default 0;

-- Flujo jerárquico de solicitudes: una evaluación PREAPROBADA no crea crédito directamente.
create table if not exists public.credit_requests(
 id uuid primary key default gen_random_uuid(),
 request_no text unique,
 evaluation_id uuid references public.business_evaluations(id) on delete restrict,
 client_id uuid not null references public.clients(id) on delete restrict,
 product_id uuid,
 amount numeric(14,2) not null,
 installments integer not null,
 interest_rate numeric(8,4) default 0,
 frequency text default 'Mensual',
 first_due date,
 status text not null default 'PENDIENTE_APROBACION' check(status in ('PENDIENTE_APROBACION','APROBADA','RECHAZADA','ANULADA')),
 created_by uuid references auth.users(id),
 approved_by uuid references auth.users(id),
 approved_at timestamptz,
 credit_id uuid references public.credits(id) on delete set null,
 created_at timestamptz default now()
);
alter table public.credits add column if not exists approved_at timestamptz;
alter table public.credits add column if not exists approved_by uuid references auth.users(id);
alter table public.credits add column if not exists disbursed_at timestamptz;
alter table public.credits add column if not exists disbursed_by uuid references auth.users(id);
alter table public.credits add column if not exists canceled_at timestamptz;
alter table public.credits add column if not exists canceled_by uuid references auth.users(id);
alter table public.credits add column if not exists cancellation_reason text;
alter table public.credit_requests enable row level security;
create policy "auth credit requests" on public.credit_requests for all to authenticated using (true) with check (true);

-- Flujo jerárquico de solicitudes: una evaluación PREAPROBADA no crea crédito directamente.
create table if not exists public.credit_requests(
 id uuid primary key default gen_random_uuid(), request_no text unique,
 evaluation_id uuid references public.business_evaluations(id) on delete restrict,
 client_id uuid not null references public.clients(id) on delete restrict,
 product_id uuid, amount numeric(14,2) not null, installments integer not null,
 interest_rate numeric(8,4) default 0, frequency text default 'Mensual', first_due date,
 status text not null default 'PENDIENTE_APROBACION' check(status in ('PENDIENTE_APROBACION','APROBADA','RECHAZADA','ANULADA')),
 created_by uuid references auth.users(id), approved_by uuid references auth.users(id), approved_at timestamptz,
 credit_id uuid references public.credits(id) on delete set null, created_at timestamptz default now()
);
alter table public.credits add column if not exists approved_at timestamptz;
alter table public.credits add column if not exists approved_by uuid references auth.users(id);
alter table public.credits add column if not exists disbursed_at timestamptz;
alter table public.credits add column if not exists disbursed_by uuid references auth.users(id);
alter table public.credits add column if not exists canceled_at timestamptz;
alter table public.credits add column if not exists canceled_by uuid references auth.users(id);
alter table public.credits add column if not exists cancellation_reason text;
alter table public.credit_requests enable row level security;
create policy "auth credit requests" on public.credit_requests for all to authenticated using (true) with check (true);
